# Generated by Django 4.2.3 on 2023-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
